# Site settings
title: Roughedge AB
email: hej@roughedge.se
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://www.roughedge.se/" # the base hostname & protocol for your site

twitter_username:
github_username: roughedge-se

# Build settings
markdown: kramdown
